[versions]

appVersionName = "3.1.3"
appVersionCode = "356"

acra = "5.13.1"
android-minSdk = "26"
android-compileSdk = "36"
android-targetSdk = "36"

agp = "8.13.2"
appUpdateKtx = "2.1.0"
revenuecat-purchases-kmp = "2.2.17+17.26.1"
composeMultiplatform = "1.10.0"
coreSplashscreen = "1.2.0"
kotlin = "2.3.0"
kotlinxCollectionsImmutable = "0.4.0"
kotlinxDatetimeNames = "0.1.1"
ksp = "2.3.4"

kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
kotlinx-datetime = "0.7.1"
desugar_jdk_libs = "2.1.5"

androidx-lifecycle = "2.10.0"
androidx-activity-compose = "1.12.2"
androidx-core-ktx = "1.17.0"
androidx-navigation-compose = "2.9.6"
androidx-paging = "3.4.0-beta01"
androidx-datastore = "1.2.0"
androidx-media = "1.7.1"
androidx-documentfile = "1.1.0"
androidx-room = "2.8.4"
sqlite = "2.6.2"
compottie = "2.0.2"
navigationCompose = "2.9.1"
reviewKtx = "2.0.2"

compose-icons-eva = "1.1.1"
koin = "4.1.1"
okio = "3.16.4"
kermit = "2.0.8"
mikepenz-aboutlibraries = "13.2.1"
spotless = "8.1.0"

androidx-test-junit = "1.3.0"
espresso-core = "3.7.0"
robolectric = "4.16"
turbine = "1.2.1"

uiBackhandler = "1.10.0"
vico = "2.4.1"
androidchart = "3.1.0.25"

work = "2.11.0"

google-play-auth = "21.5.0"
google-play-auth-credentials = "1.5.0"
google-api-client = "2.8.1"
google-drive = "v3-rev20250717-2.0.0"
google-id = "1.1.1"

[libraries]
acra-mail = { module = "ch.acra:acra-mail", version.ref = "acra" }
acra-notification = { module = "ch.acra:acra-notification", version.ref = "acra" }
androidchart = { module = "com.github.AppDevNext:AndroidChart", version.ref = "androidchart" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "androidx-paging" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidx-paging" }
androidx-paging-testing = { group = "androidx.paging", name = "paging-testing", version.ref = "androidx-paging" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation-compose" }
androidx-media = { group = "androidx.media", name = "media", version.ref = "androidx-media" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "androidx-documentfile" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateKtx" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-datetime-names = { module = "io.github.adrcotfas:kotlinx-datetime-names", version.ref = "kotlinxDatetimeNames" }
compottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compottie" }
compottie-dot = { module = "io.github.alexzhirkevich:compottie-dot", version.ref = "compottie" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "reviewKtx" }

google-play-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "google-play-auth" }
google-play-auth-credentials = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "google-play-auth-credentials"}
google-api-client = { module = "com.google.api-client:google-api-client-android", version.ref ="google-api-client" }
google-drive = {module = "com.google.apis:google-api-services-drive", version.ref = "google-drive"}
google-id = {module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "google-id"}

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines"}

desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
devsrsouza-compose-icons-eva = { module = "br.com.devsrsouza.compose.icons:eva-icons", version.ref = "compose-icons-eva" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin"}
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
roboelectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
touchlab-kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
touchlab-kermit-simple = { module = "co.touchlab:kermit-simple", version.ref = "kermit" }
mikepenz-aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "mikepenz-aboutlibraries" }
mikepenz-aboutlibraries-compose = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "mikepenz-aboutlibraries" }

purchases-core = { module = "com.revenuecat.purchases:purchases-kmp-core", version.ref = "revenuecat-purchases-kmp" }
purchases-ui = { module = "com.revenuecat.purchases:purchases-kmp-ui", version.ref = "revenuecat-purchases-kmp" }

ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "uiBackhandler" }
vico-compose = { group = "com.patrykandpatrick.vico", name = "multiplatform", version.ref = "vico" }
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "multiplatform-m3", version.ref = "vico" }

work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
mikepenz-aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "mikepenz-aboutlibraries" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
room = { id = "androidx.room", version.ref = "androidx-room" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
shared-commonTest = [
    "kotlin-test",
    "coroutines-test",
    "koin-test",
    "turbine",
    "okio-fakefilesystem",
    "androidx-paging-testing",
]
shared-androidTest = [
    "kotlin-test",
    "androidx-junit",
    "androidx-test-junit",
    "androidx-espresso-core",
    "coroutines-test",
    "roboelectric",
    "androidx-room-testing",
    "turbine"
]